---
jobs:
- name: build
  plan:
  - aggregate:
    - get: concourse-packer
    - get: concourse-packer-ci
    - get: concourse-release
      params:
        globs:
          - concourse_linux_amd64
  - task: prepare-release
    file: concourse-packer-ci/tasks/prepare-release.yml
  - task: prepare-secrets
    file: concourse-packer-ci/tasks/prepare-secrets.yml
    params:
      FILE_NAME: prepare-secrets/secrets.json
      CONTENT: |
        {"aws_access_key": {{aws-access-key-id}}, "aws_secret_key": {{aws-secret-access-key}}, "aws_region": {{aws-default-region}}}
  - put: packer-aws
    params:
      template: prepare-release/bootstrap_concourse.json
      var_file: prepare-secrets/secrets.json

resources:
- name: concourse-packer
  type: git
  source:
    uri: {{concourse-packer-git-url}}
    branch: {{concourse-packer-git-branch}}

- name: concourse-packer-ci
  type: git
  source:
    uri: {{concourse-packer-ci-git-url}}
    branch: {{concourse-packer-ci-git-branch}}

- name: concourse-release
  type: github-release
  source:
    user: concourse
    repository: concourse

- name: packer-aws
  type: packer
  source:
    aws_access_key_id: {{aws-access-key-id}}
    aws_secret_access_key: {{aws-secret-access-key}}
    region: {{aws-default-region}}

resource_types:
- name: packer
  type: docker-image
  source:
    repository: jdub/packer-resource
