---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
  - name: concourse-packer-ci

outputs:
  - name: prepare-secrets

run:
  path: concourse-packer-ci/tasks/prepare-secrets.sh

params:
  CONTENT:
  FILE_NAME:
