---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
  - name: pipeline
  - name: concourse-release

outputs:
  - name: write-file

run:
  path: pipeline/tasks/write-file.sh

params:
  CONTENT:
  FILE_NAME:
